import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { renderUnifiedEmailTemplate, renderDetailCard } from '../_shared/email-template.ts'
import { SITE_URL, SUPPORT_EMAIL, BRAND_NAME } from '../_shared/email-constants.ts'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    const { paymentId } = await req.json()

    // Fetch payment details
    const { data: payment, error } = await supabaseClient
      .from('payments')
      .select('*')
      .eq('id', paymentId)
      .single()

    if (error || !payment) {
      throw new Error('Payment not found')
    }

    // Build detail card for invoice line items
    const detailCard = renderDetailCard([
      { label: 'Invoice #', value: payment.merchant_reference },
      { label: 'Date', value: new Date(payment.created_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) },
      { label: 'Status', value: payment.status.charAt(0).toUpperCase() + payment.status.slice(1) },
      { label: 'Bill To', value: payment.user_email },
      { label: 'Payment Method', value: payment.payment_method.toUpperCase() },
    ])

    const amountCard = renderDetailCard([
      { label: payment.plan + ' Subscription', value: `${payment.currency} ${payment.amount.toFixed(2)}` },
      { label: 'Total', value: `${payment.currency} ${payment.amount.toFixed(2)}` },
    ])

    const bodyHtml = `
      ${detailCard}
      <div style="margin-top:24px;font-size:15px;line-height:20px;font-weight:600;color:#1d1d1f;">Amount</div>
      ${amountCard}
      <div style="margin-top:24px;">
        <div style="font-size:14px;line-height:20px;font-weight:600;color:#1d1d1f;margin-bottom:8px;">What's included</div>
        <ul style="margin:0;padding-left:20px;color:#424245;font-size:14px;line-height:22px;">
          <li style="margin-bottom:4px;">Unlimited exam creation and student management</li>
          <li style="margin-bottom:4px;">Advanced anti-cheating measures</li>
          <li style="margin-bottom:4px;">AI-powered question extraction</li>
          <li style="margin-bottom:4px;">Real-time analytics and reporting</li>
          <li>Priority customer support</li>
        </ul>
      </div>
    `

    const html = renderUnifiedEmailTemplate({
      preheader: `Invoice ${payment.merchant_reference} — ${payment.currency} ${payment.amount.toFixed(2)}`,
      eyebrow: 'INVOICE',
      title: 'Invoice',
      bodyHtml,
      accentColor: '#1d1d1f',
      siteUrl: SITE_URL,
      secondaryText: `For questions about this invoice, contact ${SUPPORT_EMAIL}`,
      footerNote: `This invoice was automatically generated by ${BRAND_NAME}.`,
    })

    return new Response(html, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'text/html',
      },
    })
  } catch (error) {
    console.error('Invoice generation error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    )
  }
})
